# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_audio": "00_core.ipynb",
         "play_audio": "00_core.ipynb",
         "plot_audio": "00_core.ipynb",
         "calc_spectrums": "00_core.ipynb",
         "plot_mag_spectrum": "00_core.ipynb",
         "plot_mags": "00_core.ipynb",
         "gen_sinusoid": "01_signal.ipynb",
         "plot": "01_signal.ipynb",
         "EPSILON": "02_fft.ipynb",
         "is_power_of_two": "02_fft.ipynb",
         "zero_phase_buffer": "02_fft.ipynb",
         "amplitude_to_decibels": "02_fft.ipynb",
         "decibels_to_amplitude": "02_fft.ipynb",
         "fft_analysis": "02_fft.ipynb",
         "fft_synthesis": "02_fft.ipynb",
         "get_cola_window": "03_stft.ipynb",
         "gen_frames": "03_stft.ipynb",
         "synth_frames": "03_stft.ipynb",
         "stft": "03_stft.ipynb",
         "istft": "03_stft.ipynb",
         "detect_peaks": "04_sine_model.ipynb",
         "plot_peaks": "04_sine_model.ipynb",
         "interpolate_peaks": "04_sine_model.ipynb",
         "plot_ipeaks": "04_sine_model.ipynb",
         "synth_window": "04_sine_model.ipynb",
         "Frame": "04_sine_model.ipynb",
         "sine_tracking": "04_sine_model.ipynb",
         "clean_sine_tracks": "04_sine_model.ipynb",
         "sine_model_analysis": "04_sine_model.ipynb"}

modules = ["core.py",
           "signal.py",
           "fft.py",
           "stft.py",
           "sine_model.py",
           "objects.py"]

doc_url = "https://jhartquist.github.io/rtma/"

git_url = "https://github.com/jhartquist/rtma/tree/master/"

def custom_doc_links(name): return None
