# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_audio": "00_core.ipynb",
         "play_audio": "00_core.ipynb",
         "plot_audio": "00_core.ipynb",
         "calc_spectrums": "00_core.ipynb",
         "plot_mag_spectrum": "00_core.ipynb",
         "gen_sinusoid": "01_signal.ipynb",
         "plot": "01_signal.ipynb",
         "is_power_of_two": "02_fft.ipynb",
         "zero_phase_buffer": "02_fft.ipynb",
         "fft_analysis": "02_fft.ipynb",
         "fft_synthesis": "02_fft.ipynb"}

modules = ["core.py",
           "signal.py",
           "fft.py",
           "stft.py"]

doc_url = "https://jhartquist.github.io/rtma/"

git_url = "https://github.com/jhartquist/rtma/tree/master/"

def custom_doc_links(name): return None
