# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = ['load_audio', 'play_audio', 'plot_audio', 'plot_mags']

# Cell
from .imports import *

# Cell
def load_audio(filename: str) -> (np.array, int):
    """
    Load audio as mono.
    return: signal, sample_rate (Hz)
    """
    # TODO: handle mono/stereo
    # TODO: resample?
    sample_rate, x = wavfile.read(filename)
    if x.dtype != np.float32:
        # assuming int
        x = np.float32(x) / np.iinfo(x.dtype).max
    return x, sample_rate


# Cell
def play_audio(x, sr):
    display(Audio(x, rate=sr, normalize=False))

# Cell
def plot_audio(x: np.array, sr: int = 44100, figsize=(14,2)):
    """
    Plot a signal in the time domain.
    """
    t = np.arange(len(x)) / sr
    plt.figure(figsize=figsize)
    plt.xlabel('time (s)')
    plt.ylabel('amplitude')
    plt.ylim([-1, 1])
    plt.plot(t, x)
    plt.show()

# Cell
def plot_mags(m_xs, max_bin=None):
    if max_bin:
        m_xs = m_xs[:,:max_bin+1]
    plt.figure(figsize=(10, 6))
    plt.imshow(m_xs.T, aspect='auto', interpolation='nearest', origin='lower')
    plt.xlabel('time (frames)')
    plt.ylabel('frequency (fftbins)')
    plt.show()