# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_sine_model.ipynb (unless otherwise specified).

__all__ = ['detect_peaks', 'plot_peaks', 'interpolate_peaks', 'plot_ipeaks', 'detect_peaks']

# Cell
from .imports import *
from .core import *
from .signal import *
from .fft import *
from .stft import *

# Cell
def detect_peaks(x, thresh):
    # first and last cannot be peaks
    above_thresh = np.greater(x[1:-1], thresh)
    gt_before = np.greater(x[1:-1], x[:-2])
    gt_after =  np.greater(x[1:-1], x[2:])
    is_peak = above_thresh & gt_before & gt_after
    peaks_i = is_peak.nonzero()[0] + 1
    return peaks_i

# Cell
def plot_peaks(x, peak_i, t=None):
    plt.figure(figsize=(10, 6))
    plt.plot(x)
    plt.plot(peak_i, x[peak_i], marker='x', color='r', linestyle='', markeredgewidth=1.5)
    if t is not None:
        plt.axhline(t, c='g')

# Cell
def interpolate_peaks(x, peak_i):
    a, b, c = x[peak_i-1], x[peak_i], x[peak_i+1]
    ipeak_i = peak_i + 0.5 * (a - c) / (a - 2*b + c)
    ipeak_v = b - 0.25 * (a - c) * (ipeak_i - peak_i)
    return ipeak_i, ipeak_v

# Cell
def plot_ipeaks(x, ipeak_i, ipeak_v, peak_i=None, t=None):
    plt.figure(figsize=(10, 6))
    plt.plot(x)
    plt.plot(ipeak_i, ipeak_v, marker='x', color='g', linestyle='', markeredgewidth=1.5)
    if peak_i is not None:
        plt.plot(peak_i, x[peak_i], marker='x', color='r', linestyle='', markeredgewidth=1.5)
    if t is not None:
        plt.axhline(t, c='g')

# Cell
def detect_peaks(x, thresh):
    # first and last cannot be peaks
    above_thresh = np.greater(x[1:-1], thresh)
    gt_before = np.greater(x[1:-1], x[:-2])
    gt_after =  np.greater(x[1:-1], x[2:])
    is_peak = above_thresh & gt_before & gt_after
    peaks_i = is_peak.nonzero()[0] + 1
    return peaks_i