# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_stft.ipynb (unless otherwise specified).

__all__ = ['gen_frames']

# Cell
from .imports import *
from .core import *
from .signal import *
from .fft import *

# Cell
def gen_frames(x, n_window, n_hop, window = None):
    n_overlap = n_window - n_hop
    x = np.pad(x, (n_overlap, 0), mode='constant')
    i = 0
    while i < x.size:
        frame = x[i:i+n_window]
        if frame.size < n_window:
            frame = np.pad(frame, (0, n_window-frame.size), mode='constant')
        if window is not None:
            frame = frame * window
        yield frame
        i += n_hop